In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
df = pd.read_parquet('/workspaces/mlops-zoomcamp-leo/01-intro/yellow_tripdata_2025-01.parquet', engine='fastparquet')

In [4]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,5.1,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,7.2,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.8,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0

In [5]:
import sklearn

In [6]:
sklearn.__version__

'1.8.0'

In [12]:
df.tpep_pickup_datetime - df.tpep_dropoff_datetime

0         -1 days +23:51:39
1         -1 days +23:57:27
2         -1 days +23:58:03
3         -1 days +23:54:26
4         -1 days +23:56:28
                 ...
3475221   -1 days +23:45:19
3475222   -1 days +23:33:02
3475223   -1 days +23:43:58
3475224   -1 days +23:39:42
3475225   -1 days +23:49:15
Length: 3475226, dtype: timedelta64[us]

In [13]:
pd.to_datetime(df.tpep_pickup_datetime)
pd.to_datetime(df.tpep_dropoff_datetime)

0         2025-01-01 00:26:59
1         2025-01-01 00:35:13
2         2025-01-01 00:46:01
3         2025-01-01 00:20:01
4         2025-01-01 00:25:06
                  ...
3475221   2025-01-31 23:16:29
3475222   2025-02-01 00:17:27
3475223   2025-01-31 23:43:01
3475224   2025-01-31 23:34:52
3475225   2025-02-01 00:07:27
Name: tpep_dropoff_datetime, Length: 3475226, dtype: datetime64[us]

In [20]:
df['duration'] = df.tpep_dropoff_datetime - df.tpep_pickup_datetime
df.duration.apply(lambda td: td.total_seconds() / 60)   # transform seconds to min to each element

0           8.350000
1           2.550000
2           1.950000
3           5.566667
4           3.533333
             ...
3475221    14.683333
3475222    26.966667
3475223    16.033333
3475224    20.300000
3475225    10.750000
Name: duration, Length: 3475226, dtype: float64

In [21]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,duration
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,...,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.00,0 days 00:08:21
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,...,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.00,0 days 00:02:33
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,...,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.00,0 days 00:01:57
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,...,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.00,0 days 00:05:34
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,...,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.00,0 days 00:03:32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475221,2,2025-01-31 23:01:48,2025-01-31 23:16:29,NaN,3.35,NaN,None,79,237,0,...,0.0,0.5,0.00,0.0,1.0,20.60,NaN,NaN,0.75,0 days 00:14:41
3475222,2,2025-01-31 23:50:29,2025-02-01 00:17:27,NaN,8.73,NaN,None,161,116,0,...,0.0,0.5,0.00,0.0,1.0,32.89,NaN,NaN,0.75,0 days 00:26:58
3475223,2,2025-01-31 23:26:59,2025-01-31 23:43:01,NaN,2.64,NaN,None,144,246,0,...,0.0,0.5,0.00,0.0,1.0,19.66,NaN,NaN,0.75,0 days 00:16:02
3475224,2,2025-01-31 23:14:34,2025-01-31 23:34:52,NaN,3.16,NaN,None,142,107,0,...,0.0,0.5,0.00,0.0,1.0,22.30,NaN,NaN,0.75,0 days 00:20:18
3475225,2,2025-01-31 23:56:42,2025-02-01 00:07:27,NaN,2.29,NaN,None,237,238,0,...,0.0,0.5,0.00,0.0,1.0,16.09,NaN,NaN,0.00,0 days 00:10:45

In [ ]:
# Now check the distribution of the duration